Repository final-project-09a/todaygames, pull requests merged in 2024-02, with the labels that each got.

#102 [Feature/uiux] UI/UX 개선, 최적화 작업
  src/assets/img/googlelogo.png
  src/assets/img/kakao_login_large_narrow.png
  src/assets/img/kakao_login_medium_wide.png
  src/assets/img/kakaologo.png
  src/assets/img/web_light_rd_SU@1x.png
  src/common/Tag.tsx
  src/components/Header/Header.tsx
  src/components/board/BoardList.tsx
  src/components/detailpage/GameTitle.tsx
  src/components/detailpage/SystemRequirements.tsx
  src/components/mypage/MyBookMark.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/detail/Detail.tsx
  src/pages/login/Login.tsx
  src/pages/login/styles.ts
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
  src/pages/search/Search.tsx
Labels: 리팩토링, UI

#103 update: 더보기 버튼 구현 api 수정 (#94)
  src/api/comments.ts
  src/api/likes.ts
  src/api/post.ts
  src/components/board/BoardList.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/register/Register.tsx
  src/types/supabaseTable.d.ts
Labels: 리팩토링

#105 소셜 로그인시 마이페이지 조건부 렌더링
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyCommunity.tsx
Labels: 기능

#106 [Feature/uiux] 무한스크롤 구현 및 장르별 필터 구현, 코드 리팩토링
  src/api/games.ts
  src/api/likes.ts
  src/api/post.ts
  src/common/Button.tsx
  src/components/board/BoardCategory.tsx
  src/components/board/BoardList.tsx
  src/components/comment/ReplyBox.tsx
  src/components/homepage/GenreCard.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/board/Board.tsx
  src/pages/boardDetail/style.ts
  src/pages/login/styles.ts
  src/pages/mypage/styles.ts
  src/pages/register/styles.ts
  src/pages/search/styles.ts
  src/pages/signup/styles.ts
  src/redux/config/configStore.ts
  src/redux/modules/boardSlice.ts
  src/styles/GlobalStyle.tsx
Labels: 리팩토링, 기능, UI

#109 [Feature/review] 게시글 등록 시 별점, 한줄평 추가 / 이미지 로딩 오류 수정
  src/api/post.ts
  src/api/supabaseData.ts
  src/common/Tag.tsx
  src/components/board/BoardList.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyBookMark.tsx
  src/components/mypage/MyCommunity.tsx
  src/components/mypage/MypageNav.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/edit/EditPost.tsx
  src/pages/edit/index.ts
  src/pages/edit/styles.ts
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
  src/redux/modules/postSlice.ts
  src/types/boardDetail.d.ts
  src/types/global.d.tsx
  src/types/supabaseTable.d.ts
Labels: 기능, UI

#110 마이페이지 수정 삭제 기능/기타 ui 수정
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/signup/signup.tsx
Labels: 버그, 수정

#111 [Feature/review] 게임 상세페이지에 리뷰, 평점 캐러샐로 보여주기
  src/api/post.ts
  src/api/user.ts
  src/components/detailpage/Review.tsx
  src/pages/detail/Detail.tsx
  src/types/boardDetail.d.ts
Labels: 기능, UI

#113 Feat/filter 인기순, 최신순 , 검색기능 완료
  src/api/post.ts
  src/components/board/BoardCategory.tsx
  src/components/board/BoardList.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/board/Board.tsx
  src/redux/modules/boardSlice.ts
Labels: 리팩토링, 기능, 수정

#115 Feature/post 대댓글 기능구현 완료 UI수정 완료
  src/api/comments.ts
  src/api/post.ts
  src/assets/img/comments_icon.png
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/boardDetail/style.ts
  src/pages/register/Register.tsx
  src/types/supabaseTable.d.ts
Labels: 리팩토링, 기능, UI

#116 Feat/seach 검색수정(게시물 타이틀, 게임이름만 검색)
  src/api/steamApis.ts
  src/components/board/BoardList.tsx
  src/components/detailpage/Review.tsx
  src/components/detailpage/SystemRequirements.tsx
  src/components/like/Like.tsx
  src/components/mypage/MyBookMark.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/register/Register.tsx
Labels: 수정

#117 Feature/post 대댓글기능구현 완료/ 대댓글 삭제기능 구현완료 / UI수정
  src/api/comments.ts
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/types/supabaseTable.d.ts
Labels: 기능, UI

#118 fix: 댓글 프로필사진 수정
  src/components/comment/Comment.tsx
Labels: 수정

#119 Feature/post
  src/api/comments.ts
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/register/Register.tsx
  src/types/supabaseTable.d.ts
Labels: 리팩토링, 기능, UI

#121 Feat/delete 게시판 삭제 렌더링 안되던것들 수정
  src/api/comments.ts
  src/components/board/BoardList.tsx
  src/pages/register/Register.tsx
  src/types/supabaseTable.d.ts
Labels: 기능, 수정

#124 Feat/postedit 게시물 수정창 수정
  src/components/board/BoardList.tsx
  src/pages/login/Login.tsx
Labels: 수정

#125 mypage 내가 쓴 글 이미지& 수정게시판 안나오는거 수정
  src/components/mypage/MyCommunity.tsx
Labels: 수정

#126 update: Footer UI 업데이트
  src/assets/img/githubIcon.png
  src/components/Footer/Footer.tsx
  src/components/Footer/styles.ts
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/shared/Router.js
Labels: 기능, UI
