Repository final-project-09a/todaygames, pull requests merged in 2024-01, with the labels that each got.

#8 [Feature/home] json-server 세팅 및 glitch 배포 진행
  package.json
  src/api/games.ts
  src/components/Footer/Footer.tsx
  src/components/homepage/recommendList.tsx
  src/components/like/Like.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/setupProxy.ts
  src/shared/supabase.ts
  yarn.lock
Labels: 기능

#11 [Feature/home] 헤더 ui
  src/api/games.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/homepage/GenreFilter.tsx
  src/components/homepage/NewGames.tsx
  src/components/homepage/recommendList.tsx
  src/index.tsx
  src/pages/home/Home.tsx
  src/styles/GlobalStyle.tsx
Labels: 기능, UI

#18 [Feature/home] 이번 주 추천 리스트 기능 및 UI 작업
  public/index.html
  src/api/games.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/board/BoardDetail.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/homepage/recommendList.tsx
  src/pages/home/Home.tsx
  src/pages/home/styles.ts
  src/styles/GlobalStyle.tsx
  src/styles/theme.js
  tsconfig.json
  yarn.lock
Labels: 기능, UI

#21 [Feature/home] 상세페이지 이동 구현
  src/api/games.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/homepage/NewGameCard.tsx
  src/components/homepage/NewGames.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/homepage/recommendList.tsx
  src/pages/detail/Detail.tsx
  src/pages/home/Home.tsx
  src/shared/Router.js
Labels: 기능, UI

#19 Feature/post
  package.json
  src/api/steamApi.ts
  src/api/supabaseData.ts
  src/components/Navbar/styles.ts
  src/components/board/registerStyle.ts
  src/components/homepage/RecommendList.tsx
  src/pages/board/Register.tsx
  src/pages/home/Home.tsx
  src/pages/register/Register.tsx
  src/pages/register/index.ts
  src/pages/register/styles.ts
  src/query/keys.ts
  src/query/usePostQuery.ts
  src/shared/Router.js
  src/styles/theme.js
  src/types/global.d.tsx
  yarn.lock
Labels: 수정

#25 Feature/post
  package.json
  src/api/supabaseData.ts
  src/components/Navbar/NavBar.tsx
  src/components/board/registerStyle.ts
  src/components/homepage/RecommendList.tsx
  src/components/register/InputSet.tsx
  src/components/register/styles.ts
  src/pages/board/Board.tsx
  src/pages/board/styles.ts
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
  src/query/usePostQuery.ts
  src/shared/Router.js
  src/styles/theme.js
  src/types/global.d.tsx
  yarn.lock
Labels: 기능

#26 [Feature/genre] 장르별 필터 구현 및 캐러샐
  package.json
  src/api/games.ts
  src/api/steamApis.ts
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Navbar/styles.ts
  src/components/board/Main.tsx
  src/components/homepage/GenreCard.tsx
  src/components/homepage/GenreFilter.tsx
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/NewGameCard.tsx
  src/components/homepage/NewGames.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/homepage/RecommendList.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/components/homepage/recommendList.tsx
  src/constants/genre.ts
  src/pages/detail/Detail.tsx
  src/pages/detail/styles.ts
  src/pages/home/Home.tsx
  src/pages/register/Register.tsx
  src/query/keys.ts
  yarn.lock
Labels: 기능, UI

#28 style: 새로 나온 게임 UI 수정 (#27)
  src/common/Button.tsx
  src/common/Tag.tsx
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/homepage/NewGameCard.tsx
  src/components/homepage/NewGames.tsx
  src/pages/home/Home.tsx
  src/styles/theme.js
Labels: UI

#30 Feat/board main
  src/components/board/BoardCategory.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/BoardRegister.tsx
  src/components/board/Main.tsx
  src/pages/board/Board.tsx
Labels: 버그

#34 [Feature/detail] user 전역 상태 관리 세팅
  package.json
  src/api/games.ts
  src/api/steamApi.ts
  src/api/userInfo.ts
  src/common/MoreViewButton.tsx
  src/components/detailpage/GameDescription.tsx
  src/components/detailpage/GameInfo.tsx
  src/components/detailpage/GameTitle.tsx
  src/components/detailpage/RelationGames.tsx
  src/components/detailpage/ScreenShotSlide.tsx
  src/components/detailpage/SystemReqirement.tsx
  src/pages/detail/Detail.tsx
  src/pages/detail/styles.ts
  src/pages/home/Home.tsx
  src/pages/home/styles.ts
  src/pages/mypage/mypage.tsx
  src/query/keys.ts
  src/redux/config/configStore.ts
  src/redux/modules/gameSlice.ts
  src/redux/modules/userSlice.ts
  src/userSlice.ts
  yarn.lock
Labels: 기능

#35 [Feature/detail] 게임 상세페이지 기능 및 UI 구현 완료
  src/api/games.ts
  src/api/userInfo.ts
  src/common/MoreViewButton.tsx
  src/components/detailpage/GameDescription.tsx
  src/components/detailpage/GameInfo.tsx
  src/components/detailpage/RelatedGames.tsx
  src/components/detailpage/RelationGames.tsx
  src/components/detailpage/ScreenShotSlide.tsx
  src/components/detailpage/SystemReqirement.tsx
  src/components/detailpage/SystemRequirements.tsx
  src/components/homepage/GenreCard.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/pages/detail/Detail.tsx
  src/pages/detail/styles.ts
  src/redux/modules/gameSlice.ts
Labels: 기능, UI

#39 Feature/post
  src/components/board/Main.tsx
  src/components/register/Modal.tsx
  src/pages/register/Register.tsx
  src/shared/Router.js
  yarn.lock
Labels: 기능, UI

#43 [Feature/navbar] 네브바 UI 및 supabase 전역상태로 구현
  src/App.tsx
  src/AuthenticationLayer.tsx
  src/api/games.ts
  src/api/post.ts
  src/api/steamApis.ts
  src/api/supabaseData.ts
  src/api/user.ts
  src/assets/icons/accountIcon.svg
  src/assets/icons/searchIcon.svg
  src/components/Footer/Footer.tsx
  src/components/Header/styles.ts
  src/components/Navbar/NavBar.tsx
  src/components/Navbar/Search.tsx
  src/components/Navbar/styles.ts
  src/components/board/BoardDetail.tsx
  src/components/board/Main.tsx
  src/components/comment/Comment.tsx
  src/components/detailpage/ScreenShotSlide.tsx
  src/components/homepage/NewGames.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/mypage/mypage.tsx
  src/pages/signup/signup.tsx
  src/query/usePostQuery.ts
  src/redux/modules/userSlice.ts
  src/shared/supabase.ts
Labels: 버그, 기능, UI

#45 Feature/post
  src/components/register/Modal.tsx
  src/components/register/style.ts
  src/pages/mypage/mypage.tsx
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
Labels: 기능, UI

#48 [Feature/header carousel] 헤더 캐러샐 UI 수정 및 장르별 탐색 UI 및 기능 추가 구현
  src/assets/icons/success.svg
  src/common/CustomCarousel.tsx
  src/common/SuccessModal.tsx
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Navbar/GameSearch.tsx
  src/components/Navbar/NavBar.tsx
  src/components/Navbar/styles.ts
  src/components/detailpage/ScreenShotSlide.tsx
  src/components/homepage/GenreCard.tsx
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/constants/genre.ts
  src/pages/home/styles.ts
  src/pages/login/Login.tsx
Labels: 기능, UI

#50 update: post page UI 조건렌더링 업데이트, 검색기능 완료#49
  src/api/supabaseData.ts
  src/components/register/Modal.tsx
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
  src/types/global.d.tsx
Labels: 기능, UI

#52 Feature/post supabase 연결
  src/api/supabaseData.ts
  src/pages/register/Register.tsx
  src/types/global.d.tsx
Labels: 기능

#54 [Feature/mypage nav] 커뮤니티 페이지 장르별 필터 기능 구현
  src/assets/icons/boomarkIcon.svg
  src/assets/icons/communityIcon.svg
  src/assets/icons/editProfileIcon.svg
  src/components/Header/Header.tsx
  src/components/board/BoardCategory.tsx
  src/components/board/BoardDetail.tsx
  src/components/board/Main.tsx
  src/components/mypage/MypageNav.tsx
  src/pages/board/Board.tsx
  src/pages/mypage/mypage.tsx
  src/pages/mypage/styles.ts
Labels: 기능

#55 [Feature/mypage nav] 마이페이지 UI 수정 및 기능구현
  src/assets/icons/cancelIcon.svg
  src/common/Button.tsx
  src/common/Tag.tsx
  src/components/Navbar/NavBar.tsx
  src/components/mypage/MypageNav.tsx
  src/constants/genre.ts
  src/pages/mypage/mypage.tsx
  src/pages/mypage/styles.ts
  src/redux/modules/userSlice.ts
  src/shared/Router.js
Labels: 기능, UI

#63 Feature/post #62
  src/api/supabaseData.ts
  src/assets/img/editBtn.png
  src/assets/img/removeButton.png
  src/components/board/Main.tsx
  src/pages/board/BoardDetail.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/boardDetail/style.ts
  src/pages/register/Register.tsx
  src/pages/register/styles.ts
  src/redux/modules/userSlice.ts
  src/shared/Router.js
  src/shared/supabase.type.ts
  src/types/global.d.tsx
Labels: 기능, UI

#68 update: BoardDetail 페이지에서 image를 supabase storage로 업로드 하는 기능 구현 / 수정&…
  src/components/register/AlertModal.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/register/Register.tsx
  src/types/register.d.tsx
Labels: 기능, UI

#70 [Feature/genrefilter] 홈 화면 스켈레톤 UI 적용, 장르 필터 화면 깜빡임 해결
  package.json
  src/AuthenticationLayer.tsx
  src/api/comments.ts
  src/api/games.ts
  src/api/post.ts
  src/api/replies.ts
  src/api/supabaseData.ts
  src/api/user.ts
  src/assets/icons/headerLeftIcon.svg
  src/assets/icons/headerNextIcon.svg
  src/assets/icons/nextIcon.svg
  src/assets/icons/prevIcon.svg
  src/common/CustomCarousel.tsx
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Navbar/NavBar.tsx
  src/components/board/BoardList.tsx
  src/components/detailpage/RelatedGames.tsx
  src/components/detailpage/SystemRequirements.tsx
  src/components/homepage/GenreCard.tsx
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/NewGameCard.tsx
  src/components/homepage/NewGames.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/homepage/RecommendList.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MypageNav.tsx
  src/components/skeletons/GenreListSkeleton.tsx
  src/components/skeletons/HeaderTitleSkeleton.tsx
  src/components/skeletons/NewGameCardSkeleton.tsx
  src/components/skeletons/RecommendCardSkeleton.tsx
  src/constants/genre.ts
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/detail/Detail.tsx
  src/pages/home/styles.ts
  src/pages/login/Login.tsx
  src/pages/mypage/index.ts
  src/pages/register/Register.tsx
  src/pages/signup/signup.tsx
  src/styles/theme.ts
  src/types/games.d.ts
  src/types/supabase.ts
  src/types/supabaseTable.d.ts
  src/util/sliderIcons.tsx
  yarn.lock
Labels: 기능, UI

#71 [feature/genrefilter] 슬라이드 3종 세팅 및 UI 변경
  src/components/detailpage/GameInfo.tsx
  src/components/detailpage/GameTitle.tsx
  src/components/detailpage/RelatedGames.tsx
  src/components/detailpage/ScreenShotSlide.tsx
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/components/skeletons/GenreListSkeleton.tsx
  src/pages/detail/Detail.tsx
  src/redux/modules/gameSlice.ts
Labels: 기능, UI

#73 비밀번호 변경 기능 실시간 유효성검사 UI 구성
  src/components/mypage/EditProfile.tsx
  src/pages/mypage/styles.ts
Labels: 기능, UI

#74 [Feature/home UI] 홈 화면 슬라이더 UI 변경
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/detailpage/GameInfo.tsx
  src/components/detailpage/GameTitle.tsx
  src/components/detailpage/RelatedGames.tsx
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/components/skeletons/GenreListSkeleton.tsx
  src/components/skeletons/HeaderTitleSkeleton.tsx
  src/redux/modules/gameSlice.ts
Labels: 기능, UI

#75 update: 홈 게임 검색 기능 구현 (#41)
  public/favicon.png
  public/index.html
  src/assets/icons/folderIcon.svg
  src/assets/logo/logo3.png
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Navbar/GameSearch.tsx
  src/components/Navbar/NavBar.tsx
  src/components/Navbar/styles.ts
  src/components/homepage/GenreSlider.tsx
  src/components/homepage/SelectedGenreCard.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/pages/search/Search.tsx
  src/pages/search/index.ts
  src/pages/search/styles.ts
  src/shared/Router.js
  src/types/supabaseTable.d.ts
Labels: 기능, UI

#76 마이 페이지 내가쓴글 화면 구현
  src/components/mypage/MyCommunity.tsx
  src/pages/mypage/styles.ts
Labels: 기능, UI

#77 [Feature/bookmark] 북마크 기능 구현 및 supabase 데이터 연결
  src/api/bookmark.ts
  src/assets/icons/bookmarkIcon.svg
  src/assets/icons/heartIcon.svg
  src/assets/icons/redHeartIcon.svg
  src/components/detailpage/GameInfo.tsx
  src/components/detailpage/GameTitle.tsx
  src/components/detailpage/RelatedGames.tsx
  src/components/homepage/SelectedGenreList.tsx
  src/query/keys.ts
  src/types/games.d.ts
  src/types/supabaseTable.d.ts
Labels: 기능, UI

#80 마이페이지 찜목록
  src/components/mypage/MyBookMark.tsx
Labels: 기능, UI

#81 Feature/post
  src/api/post.ts
  src/api/supabaseData.ts
  src/assets/img/front-end.png
  src/assets/img/gpu.png
  src/assets/img/modem.png
  src/assets/img/psu.png
  src/assets/img/tower-pc.png
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/boardDetail/style.ts
  src/pages/register/Register.tsx
  src/redux/modules/postSlice.ts
  src/types/boardDetail.d.ts
  src/types/global.d.tsx
  src/types/register.d.tsx
  src/types/supabaseTable.d.ts
  src/util/date.ts
Labels: 기능, UI

#82 fix: 마이페이지 내가 쓴 글 수정 삭제 dropdown (#78)
  src/components/board/BoardList.tsx
  src/components/mypage/MyCommunity.tsx
  src/pages/board/Board.tsx
Labels: 기능, UI

#83 update: 수정, 삭제 기능 구현 1차 (#78)
  src/components/board/BoardList.tsx
  src/pages/edit/EditPost.tsx
  src/pages/edit/index.ts
  src/pages/edit/styles.ts
  src/pages/mypage/mypage.tsx
  src/pages/register/Register.tsx
  src/shared/Router.js
Labels: 기능

#85 Feature/post 1차배포 전 마지막수정
  src/api/comments.ts
  src/api/post.ts
  src/api/supabaseData.ts
  src/assets/img/comment.png
  src/assets/img/front-end.png
  src/assets/img/gpu.png
  src/assets/img/like.png
  src/assets/img/modem.png
  src/assets/img/psu.png
  src/assets/img/tower-pc.png
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/boardDetail/style.ts
  src/query/useReplyQuery.ts
  src/types/supabaseTable.d.ts
Labels: 배포

#89 [Feature/UI] 전체적인 디테일 수정
  src/assets/icons/drpodown.svg
  src/assets/img/kakao_login_large_narrow.png
  src/assets/img/kakao_login_medium_narrow.png
  src/assets/img/logo.png
  src/common/Button.tsx
  src/components/Header/Header.tsx
  src/components/Header/styles.ts
  src/components/Navbar/NavBar.tsx
  src/components/Navbar/styles.ts
  src/components/board/BoardList.tsx
  src/components/homepage/NewGameCard.tsx
  src/components/homepage/RecommendCard.tsx
  src/components/mypage/EditProfile.tsx
  src/components/mypage/MyBookMark.tsx
  src/components/mypage/MyCommunity.tsx
  src/components/mypage/MypageNav.tsx
  src/components/skeletons/GenreListSkeleton.tsx
  src/pages/boardDetail/style.ts
  src/pages/home/Home.tsx
  src/pages/login/Login.tsx
  src/pages/login/styles.ts
  src/pages/mypage/mypage.tsx
  src/pages/mypage/styles.ts
  src/pages/register/styles.ts
  src/pages/search/index.ts
  src/pages/searchUserInfo/SearchUserInfo.tsx
  src/pages/searchUserInfo/index.ts
  src/pages/searchUserInfo/styles.ts
  src/pages/signup/signup.tsx
  src/pages/signup/styles.ts
  src/redux/modules/userSlice.ts
  src/shared/Router.js
  src/styles/GlobalStyle.tsx
  src/types/supabase.ts
Labels: 버그, 기능, UI

#91 마이페이지 내가쓴글 전체적으로 수정
  src/components/mypage/MyCommunity.tsx
Labels: 리팩토링, 기능, UI

#92 Feature/post 좋아요 및 댓글 & UI 업데이트
  src/api/comments.ts
  src/api/likes.ts
  src/api/post.ts
  src/components/comment/Comment.tsx
  src/components/mypage/MypageNav.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/pages/boardDetail/style.ts
  src/query/keys.ts
  src/query/useCommentQuery.ts
  src/query/useReplyQuery.ts
  src/types/supabaseTable.d.ts
  src/util/date.ts
Labels: 기능, UI

#93 update: 게시글 삭제 기능 구현 (#88)
  src/api/post.ts
  src/components/board/BoardList.tsx
  src/components/mypage/MyCommunity.tsx
Labels: 기능

#96 Feature/post 좋아요기능 정상구현 & 댓글 UI 및 기능구현 60%구현
  src/api/comments.ts
  src/assets/img/send.png
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/types/supabaseTable.d.ts
Labels: 기능, UI

#97 css 회원가입시 실시간 유효성검사 가능
  src/pages/signup/signup.tsx
  src/pages/signup/styles.ts
Labels: 기능, UI

#101 Feature/post 실시간댓글, 실시간 좋아요, 댓글 수, 좋아요 수 모두 완료(UI미완성)#84
  src/api/comments.ts
  src/components/comment/Comment.tsx
  src/components/comment/ReplyBox.tsx
  src/pages/boardDetail/BoardDetail.tsx
  src/types/supabaseTable.d.ts
Labels: 기능, 수정
